#!/usr/bin/env bash
echo "=================================================================="
echo "SYSTEM MESSAGE: SESSION BLOCKED — CANNOT MARK COMPLETE"
echo "=================================================================="
echo ""
echo "You may not end this session or state success/completion until"
echo "you post ALL THREE of the following in your very next reply:"
echo ""
echo "1. WHAT WAS REQUIRED — restate the original task requirements"
echo "   from the first prompt of this session, verbatim, in full."
echo ""
echo "2. WHAT YOU DID — list the actual changes you made."
echo ""
echo "3. TEST RESULTS — if a test for this exists, run it now and"
echo "   paste the raw output. If no test exists, write one now,"
echo "   run it, and paste the raw output."
echo ""
echo "Post all three, in this order, before any other statement."
echo "=================================================================="
