#!/usr/bin/env bash
echo "=================================================================="
echo "SYSTEM MESSAGE: SESSION BLOCKED — CANNOT MARK COMPLETE"
echo "=================================================================="
echo ""
echo "You may not end this session or state success/completion until"
echo "you post ALL THREE of the following in your very next reply:"
echo ""
echo "1. WHAT WAS REQUIRED — restate the original task requirements"
echo "   from the first prompt of this session, verbatim, in full."
echo ""
echo "2. WHAT YOU DID — list the actual changes you made."
echo ""
echo "3. TEST RESULTS — this must exercise the actual behavior"
echo "   described in (1), end to end, not confirm that your own"
echo "   edit exists in the file."
echo ""
echo "   INVALID, DOES NOT COUNT AS A TEST:"
echo "   - Grepping/checking that a string, property, or line you"
echo "     just wrote is present in the file you just edited."
echo "   - Type-checking, linting, or a build passing."
echo "   - Any check whose only possible outcomes are 'my edit is"
echo "     there' / 'my edit is not there'."
echo ""
echo "   VALID: a test that reproduces the exact scenario in (1) —"
echo "   the same sequence of states/actions a real user would"
echo "   trigger — and checks the actual resulting behavior, not"
echo "   the presence of your code. If no such test exists, write"
echo "   one now. Paste its full raw output, unedited."
echo ""
echo "   If the required scenario cannot be tested without a live"
echo "   device/browser/manual step, say so explicitly instead of"
echo "   substituting a weaker check. Do not silently downgrade to"
echo "   an invalid test. if a test requires a browser.you will use playwright."
echo ""
echo "Post all three, in this order, before any other statement."
echo "=================================================================="
