name: ConfigCat Scan
on: [push]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: configcat/scan-action@v2
        name: Scan Shared
        with:
          api-user: ${{ secrets.CONFIGCAT_API_USER }}
          api-pass: ${{ secrets.CONFIGCAT_API_PASS }}
          config-id: ${{ secrets.CONFIG_ID_SHARED }}
      - uses: configcat/scan-action@v2
        name: Scan Frontend
        with:
          api-user: ${{ secrets.CONFIGCAT_API_USER }}
          api-pass: ${{ secrets.CONFIGCAT_API_PASS }}
          config-id: ${{ secrets.CONFIG_ID_FRONTEND }}
      - uses: configcat/scan-action@v2
        name: Scan Server
        with:
          api-user: ${{ secrets.CONFIGCAT_API_USER }}
          api-pass: ${{ secrets.CONFIGCAT_API_PASS }}
          config-id: ${{ secrets.CONFIG_ID_SERVER }}
